services:
  edge-service:
    image: 'edge-service'
    container_name: 'edge-service'
    ports:
      - '4000:4000'
    depends_on:
      - 'polar-redis'
      - 'grafana-lgtm'
    environment:
      - 'BOOK_CATALOG_SERVICE_URL=http://catalog-service:4001'
      - 'BOOK_ORDER_SERVICE_URL=http://order-service:4002'
      - 'SPRING_DATA_REDIS_HOST=polar-redis'
      - 'JAVA_TOOL_OPTIONS: --enable-preview'
      - 'MANAGEMENT_OPENTELEMETRY_LOGGING_EXPORT_OTLP_ENDPOINT=http://grafana-lgtm:4318/v1/logs'
      - 'MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT=http://grafana-lgtm:4318/v1/traces'
      - 'MANAGEMENT_OTLP_METRICS_EXPORT_URL=http://grafana-lgtm:4318/v1/metrics'
  catalog-service:
    image: 'catalog-service'
    container_name: 'catalog-service'
    ports:
      - '4001:4001'
    depends_on:
      - 'polar-postgres'
      - 'polar-redis'
      - 'grafana-lgtm'
      - 'polar-rabbitmq'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog'
      - 'SPRING_DATA_REDIS_HOST=polar-redis'
      - 'SPRING_RABBITMQ_HOST=polar-rabbitmq'
      - 'SPRING_PROFILES_ACTIVE=testdata'
      - 'JAVA_TOOL_OPTIONS: --enable-preview'
      - 'MANAGEMENT_OPENTELEMETRY_LOGGING_EXPORT_OTLP_ENDPOINT=http://grafana-lgtm:4318/v1/logs'
      - 'MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT=http://grafana-lgtm:4318/v1/traces'
      - 'MANAGEMENT_OTLP_METRICS_EXPORT_URL=http://grafana-lgtm:4318/v1/metrics'

  order-service:
    image: 'order-service'
    container_name: 'order-service'
    ports:
      - '4002:4002'
    depends_on:
      - 'polar-postgres'
      - 'polar-rabbitmq'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres:5432/polardb_catalog'
      - 'BOOK_CATALOG_SERVICE_URI=http://catalog-service:4001'
      - 'JAVA_TOOL_OPTIONS: --enable-preview'
      - 'SPRING_RABBITMQ_HOST=polar-rabbitmq'
      - 'MANAGEMENT_OPENTELEMETRY_LOGGING_EXPORT_OTLP_ENDPOINT=http://grafana-lgtm:4318/v1/logs'
      - 'MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT=http://grafana-lgtm:4318/v1/traces'
      - 'MANAGEMENT_OTLP_METRICS_EXPORT_URL=http://grafana-lgtm:4318/v1/metrics'

  dispatch-service:
    image: 'dispatch-service'
    container_name: 'book-dispatch-service'
    ports:
      - '4003:4003'
    depends_on:
      - 'polar-rabbitmq'
    environment:
      - 'SPRING_RABBITMQ_HOST=polar-rabbitmq'
      - 'JAVA_TOOL_OPTIONS: --enable-preview'
      - 'MANAGEMENT_OPENTELEMETRY_LOGGING_EXPORT_OTLP_ENDPOINT=http://grafana-lgtm:4318/v1/logs'
      - 'MANAGEMENT_OPENTELEMETRY_TRACING_EXPORT_OTLP_ENDPOINT=http://grafana-lgtm:4318/v1/traces'
      - 'MANAGEMENT_OTLP_METRICS_EXPORT_URL=http://grafana-lgtm:4318/v1/metrics'

  polar-postgres:
    image: 'postgres:15.1'
    container_name: 'polar-postgres'
    environment:
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

  polar-redis:
    image: 'redis:8.4.0'
    container_name: 'polar-redis'
    ports:
      - '6379:6379'

  polar-rabbitmq:
    image: 'rabbitmq:4.1.1-management'
    container_name: 'polar-rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - 'RABBITMQ_DEFAULT_USER=user'
      - 'RABBITMQ_DEFAULT_PASS=password'

  grafana-lgtm:
    image: 'grafana/otel-lgtm:latest'
    container_name: 'grafana-lgtm'
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'